name: Packing files
on:
  push:
    branches:
    - main

jobs:
  packing:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Packing all files
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Incrementar versión
      uses: mathieudutour/github-tag-action@v6.1
      id: tag
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: 'v'
          default_bump: 'minor'
          create_annotated_tag: true
          fetch_all_tags: false
    - name: Packing linux
      run: cd linux/addons && zip -r tf2sm_dependencies_linux.zip sourcemod && mv tf2sm_dependencies_linux.zip ./../.. && cd ../..
    - name: Packing linux
      run: cd windows/addons && zip -r tf2sm_dependencies_windows.zip sourcemod && mv tf2sm_dependencies_windows.zip ./../.. && cd ../..
    - name: Listing all files
      run: ls -gh
    
    - name: Publicar versión
      id: publicar
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.tag.outputs.new_tag }}
        release_name: TF2 Dependencies v${{ steps.tag.outputs.new_tag }}
        body: Automatized
        draft: false
        prerelease: false
    - name: Subir archivo Linux
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.publicar.outputs.upload_url }}
        asset_path: ./tf2sm_dependencies_linux.zip
        asset_name: tf2sm_dependencies_linux.zip
        asset_content_type: application/zip
    - name: Subir archivo Windows
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.publicar.outputs.upload_url }}
        asset_path: ./tf2sm_dependencies_windows.zip
        asset_name: tf2sm_dependencies_windows.zip
        asset_content_type: application/zip
